<?php
/**
 * Created by PhpStorm.
 * User: ddiallo
 * Date: 1/10/20
 * Time: 3:13 PM
 */


/**
 * Implements hook_views_data_alter().
 */
function start_enddate_filter_views_data_alter(array &$data) {

  $data['node_field_data']['start_filter'] = [
    'title' => t('Start month'),
    'filter' => [
      'title' => t('Start month'),
      'help' => 'Filter on start month and year',
      'field' => 'nid',
      'id' => 'custom_start_month_filter',
    ],
  ];

  $data['node_field_data']['end_filter'] = [
    'title' => t('End month'),
    'filter' => [
      'title' => t('End month'),
      'help' => 'Filter on end month and year',
      'field' => 'nid',
      'id' => 'custom_end_month_filter',
    ],
  ];
}